### ISSUE TITLE
Collect non-reddit links from wiki?

### ISSUE THREAD

**Issue by masklinn** [hacst/hfy2epub#3]
The collector seems to mostly work fine, however if a series happens to mix reddit posts with external links like the [Deathworlders Essential Reading Order](https://www.reddit.com/r/HFY/wiki/ref/universes/jenkinsverse/essential_reading_order) (where the "main series" posts are on an external site until chapter 37 "Grounded") then those external links are just skipped

**Comment by hacst** [comment]
Sorry for the delayed reply. Missed the notification.

I don't think collection from sites other than reddit is something that is feasible to implement in this project. hfy2epub is heavily constrained by the fact that it has to work inside of a users browser with no server component. It works for reddit because the parts of the API it uses happen to allow cross-origin access.

A native application or browser extensions would not be constrained by the same origin policy. Even then it would not be easy to reliably extract the right content out of the target site without adding special knowledge about the site to the code (e.g. about their pagination, chapterization etc.). The HFY wiki and posts more or less follow a set of conventions that can be captured reasonably well with simple heuristics. Out in the web it's the wild west ;)

There might be a place for a browser extension that tries to help you to build an EPUB from arbitrary web-content (e.g. do some Firefox reader mode like extraction + some site specific extensions and pagination heuristics) but this is not a direction I am planning to go with hfy2epub.
